import { CoursePrice, OptionPrice, AdditionalFee } from './types'

// Default course pricing data
export const defaultCourses: CoursePrice[] = [
  {
    id: '1',
    name: '【ご利用者数2万人突破】ありがとうキャンペーン',
    description:
      'おかげさまで累計ご利用者数22,200人突破！感謝の気持ちを込めてキャンペーンを開催いたします！',
    durations: [
      { time: 70, price: 13000, originalPrice: 22000, label: 'お試しフリー限定' },
      { time: 90, price: 19000, originalPrice: 27000 },
      { time: 110, price: 25000, originalPrice: 32000, label: '人気No.2コース' },
      { time: 130, price: 30000, originalPrice: 38000, label: '人気No.1コース' },
      { time: 160, price: 36000, originalPrice: 45000 },
      { time: 190, price: 42000, originalPrice: 52000 },
    ],
    features: ['本格睾丸マッサージ', '回春性感マッサージ', '密着フェザータッチ', '全身マッサージ'],
    notes: [
      'お試しコースはフリー指名限定のご案内になります',
      '回春マッサージを多め希望は、回春増し増し（有料）をオススメです',
      '「オールヌードOP」をつけて"超密着泡洗体"は至福のひと時です',
      'その他割引との併用は不可とさせて頂きます',
    ],
    category: 'campaign',
    displayOrder: 1,
    isActive: true,
    isPopular: true,
    recommendedDuration: 130,
    targetAudience: 'お店選びに迷ったら金の玉クラブへ',
    minAge: 18,
    maxAge: 70,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '密着睾丸コース',
    description: '当店自慢の本格睾丸マッサージ＆回春性感マッサージをフルに楽しんで頂けます',
    durations: [
      { time: 60, price: 16000, label: 'お試しフリー限定' },
      { time: 80, price: 21000 },
      { time: 100, price: 26000 },
      { time: 120, price: 32000, label: 'オススメ' },
      { time: 150, price: 39000 },
      { time: 180, price: 46000 },
    ],
    features: [
      '本格睾丸マッサージ',
      '回春性感マッサージ',
      '密着マッサージ',
      '全身リラクゼーション',
    ],
    notes: [
      'お試しコースはフリー指名限定のご案内になります',
      '180分以上のローングコースも対応可能でございます',
      '会員（VIP）様限定にて3週間前から事前予約も可能でございます',
    ],
    pointUsage: {
      '80': 1000,
      '100': 2000,
      '120': 2000,
      '150': 3000,
      '180+': 4000,
    },
    category: 'standard',
    displayOrder: 2,
    isActive: true,
    isPopular: false,
    recommendedDuration: 120,
    targetAudience: '本格的な睾丸マッサージをお求めの方に',
    minAge: 18,
    maxAge: 70,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default option pricing data
export const defaultOptions: OptionPrice[] = [
  {
    id: '1',
    name: '癒やしの膝枕耳かき',
    description: 'リラックスタイムの定番',
    price: 0,
    category: 'relaxation',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '密着洗髪スパ',
    description: '至福のヘッドスパ体験',
    price: 0,
    category: 'relaxation',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'オイル増し増し',
    description: 'たっぷりオイルで極上マッサージ',
    price: 0,
    category: 'special',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'キス（フレンチ）',
    description: '濃厚な時間をお楽しみください',
    price: 1000,
    category: 'special',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'パンスト',
    description: 'お好みのスタイルで',
    price: 1000,
    category: 'special',
    displayOrder: 5,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: '回春増し増し',
    description: '通常回春サービスの2倍のお時間楽しみ頂けます',
    price: 2000,
    category: 'special',
    displayOrder: 6,
    isActive: true,
    isPopular: true,
    note: '人気No.2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: '前立腺マッサージ',
    description: '究極のリラクゼーション',
    price: 2000,
    category: 'special',
    displayOrder: 7,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'オールヌード',
    description: '超密着泡洗体で至福のひと時（120分以上で混浴サービスも可）',
    price: 3000,
    category: 'special',
    displayOrder: 8,
    isActive: true,
    isPopular: true,
    note: '人気No.1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    name: 'スキンフェラ',
    description: '特別なサービス',
    price: 3000,
    category: 'special',
    displayOrder: 9,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    name: '延長30分',
    description: 'コース時間を30分延長',
    price: 8000,
    duration: 30,
    category: 'extension',
    displayOrder: 10,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default additional fees data
export const defaultAdditionalFees: AdditionalFee[] = [
  {
    id: '1',
    name: '指名料',
    type: 'range',
    value: { min: 2000, max: 5000 },
    description: 'キャストのランクにより変動',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '交通費',
    type: 'range',
    value: { min: 0, max: 5000 },
    description: 'エリアにより変動',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: '深夜料金（22:00以降）',
    type: 'percentage',
    value: 20,
    description: '基本料金の20%増',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default pricing notes
export const defaultPricingNotes = [
  '料金は全て税込価格です',
  'オプションを付け足すことで、普段とは違うより刺激的＆さらに濃厚な施術をお楽しみ頂けます',
  'セラピストにより可能オプションが違いますのでお問い合わせください',
  'お支払いは現金のみとなります',
  'キャンセル料: 当日キャンセルは料金の50%',
  'ご予約は10分単位で承ります',
]
