import { CoursePrice, OptionPrice, AdditionalFee } from './types'

// Default course pricing data
export const defaultCourses: CoursePrice[] = [
  {
    id: 'course-60',
    name: 'スタンダード 60分',
    description: 'まずはお試しに最適なベーシックコース',
    duration: 60,
    price: 16000,
    storeShare: 9600,
    castShare: 6400,
    isActive: true,
    enableWebBooking: true,
    archivedAt: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-90',
    name: 'リラックス 90分',
    description: 'しっかり癒やされたい方に人気のコース',
    duration: 90,
    price: 21000,
    storeShare: 12600,
    castShare: 8400,
    isActive: true,
    enableWebBooking: true,
    archivedAt: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'course-120',
    name: 'プレミアム 120分',
    description: '贅沢な時間を過ごせるプレミアムコース',
    duration: 120,
    price: 26000,
    storeShare: 15600,
    castShare: 10400,
    isActive: true,
    enableWebBooking: true,
    archivedAt: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default option pricing data
export const defaultOptions: OptionPrice[] = [
  {
    id: '1',
    name: '癒やしの膝枕耳かき',
    description: 'リラックスタイムの定番',
    price: 0,
    storeShare: 0,
    castShare: 0,
    category: 'relaxation',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '密着洗髪スパ',
    description: '至福のヘッドスパ体験',
    price: 0,
    storeShare: 0,
    castShare: 0,
    category: 'relaxation',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'オイル増し増し',
    description: 'たっぷりオイルで極上マッサージ',
    price: 0,
    storeShare: 0,
    castShare: 0,
    category: 'special',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'キス（フレンチ）',
    description: '濃厚な時間をお楽しみください',
    price: 1000,
    storeShare: 600,
    castShare: 400,
    category: 'special',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'パンスト',
    description: 'お好みのスタイルで',
    price: 1000,
    storeShare: 600,
    castShare: 400,
    category: 'special',
    displayOrder: 5,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: '回春増し増し',
    description: '通常回春サービスの2倍のお時間楽しみ頂けます',
    price: 2000,
    storeShare: 1200,
    castShare: 800,
    category: 'special',
    displayOrder: 6,
    isActive: true,
    isPopular: true,
    note: '人気No.2',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: '前立腺マッサージ',
    description: '究極のリラクゼーション',
    price: 2000,
    storeShare: 1200,
    castShare: 800,
    category: 'special',
    displayOrder: 7,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'オールヌード',
    description: '超密着泡洗体で至福のひと時（120分以上で混浴サービスも可）',
    price: 3000,
    storeShare: 1800,
    castShare: 1200,
    category: 'special',
    displayOrder: 8,
    isActive: true,
    isPopular: true,
    note: '人気No.1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    name: 'スキンフェラ',
    description: '特別なサービス',
    price: 3000,
    storeShare: 1800,
    castShare: 1200,
    category: 'special',
    displayOrder: 9,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    name: '延長30分',
    description: 'コース時間を30分延長',
    price: 8000,
    storeShare: 4800,
    castShare: 3200,
    duration: 30,
    category: 'extension',
    displayOrder: 10,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default additional fees data
export const defaultAdditionalFees: AdditionalFee[] = [
  {
    id: '1',
    name: '指名料',
    type: 'range',
    value: { min: 2000, max: 5000 },
    description: 'キャストのランクにより変動',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: '交通費',
    type: 'range',
    value: { min: 0, max: 5000 },
    description: 'エリアにより変動',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: '深夜料金（22:00以降）',
    type: 'percentage',
    value: 20,
    description: '基本料金の20%増',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Default pricing notes
export const defaultPricingNotes = [
  '料金は全て税込価格です',
  'オプションを付け足すことで、普段とは違うより刺激的＆さらに濃厚な施術をお楽しみ頂けます',
  'セラピストにより可能オプションが違いますのでお問い合わせください',
  'お支払いは現金のみとなります',
  'キャンセル料: 当日キャンセルは料金の50%',
  'ご予約は10分単位で承ります',
]
